apiVersion: apps/v1
kind: ReplicaSet #deployment is better than replicaSet
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template: #template for pod
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: angular-fleet-app
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    name: fleetman-queue
    app: queue
    release: 'release1'
spec:
  containers:
  - name: fleetman-queue
    image: richardchesterwood/k8s-fleetman-queue:release1
