apiVersion: v1
kind: Pod
metadata:
  name: angular-fleet-app-0-5
  labels:
    name: angular-fleet-app
    app: webapp
    release: 0-5
spec:
  containers:
  - name: angular-fleet-app
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

---

apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    name: fleetman-queue
    app: queue
    release: 'release1'
spec:
  containers:
  - name: fleetman-queue
    image: richardchesterwood/k8s-fleetman-queue:release1
