apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: webapp
    release: '0-5'
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 #nodeport has to be above 30,000
  type: NodePort #ClusterIP for internal services